language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install .
  - pip install flake8 pylint coveralls cryptography
  - python --version 2>&1 | grep -q "Python 2" && pip install mock || true
script:
- flake8 adb_shell/ && pylint adb_shell/ && coverage run --source adb_shell setup.py test
after_success:
- coveralls
